### PR TITLE
Improve cmake support.

### PR DESCRIPTION
**Pull request by combolek**
Add top-level and plater-gui CMakeLists.txt.
Add packaging support.

Tested with native Linux, Linux MingW cross-compile and native Windows MSVC.

### CODE REVIEW

**Comment by combolek** [comment]
ping

**Comment by Gregwar** [comment]
Your branch is broken for me (Ubuntu 18.04)

```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/lib/ccache/cc
-- Check for working C compiler: /usr/lib/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at CMakeLists.txt:70 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "plater".


-- Configuring incomplete, errors occurred!
See also "/tmp/Plater/plater/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/Plater/plater/build/CMakeFiles/CMakeError.log".
```

**Comment by combolek** [comment]
Sorry about that, different cmake version. Should be fixed now.
Thanks

**Comment by Gregwar** [comment]
Thanks for contributing

**Pull request merged**
