### PR TITLE
Visual Studio 2017 porting changes

### PR DESCRIPTION
**Pull request by combolek**

### CODE REVIEW

**Comment by combolek** [comment]
Any hope this getting looked at?
Thanks

**Comment by combolek** [comment]
ping?

**Comment by combolek** [comment]
Is there any chance for this change being merged? Are you open to contributions from others?
I would appreciate any response.

**Comment by Gregwar** [comment]
Thanks for contributing
Sorry for the delay

**Comment by combolek** [comment]
Thanks, np!

**Pull request merged**
